[package]
name = "twitter-bot-rs"
version = "0.1.0"
authors = ["Julien Delange <julien@gunnm.org>"]
edition = "2021"

[dependencies]
dirs2 = "3.0.1"
rand = "0.8.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
oauth-client = "0.6.1"
twitter-api = "0.5.0"
